version: 2

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy App
          command: |
            ssh centos@20.228.142.174 "cd /var/www/nodebackend/ && sudo git pull && cd /home/centos && sudo pm2 restart app"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: dev