name: SFTP CI
 
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  
  pull_request:
    branches: ["dev"]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        runs-on: [self-hosted,frontend]
        strategy:
            matrix:
                node-version: [ 16.x]
        steps:
            - uses: actions/checkout@v3
            - name: Node LTS versions
              uses: msimerson/node-lts-versions@v1.1.1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              env:
                  FORCE_COLOR: 0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
                  cache-dependency-path: "./client/package-lock.json"
        
            - name: Start project
            - run: cd client && npm install
            - run: pm2 restart frontend
      
